### ISSUE TITLE
[Bug Report] Delete wiki

### ISSUE THREAD

**Issue by CodeGuy92** [leahcimtowebsites/leahcimto.com#10]
**Describe the bug**
There is a useless wiki, can it get deleted? I don't have admin, sooo. Delete it for me.

**Screenshots**
I don't have any screenshots.

**Device info**
Windows 10, Latest Update. Browser is Chrome.

**Comment by CodeGuy92** [comment]
And so is the projects & actions tab. Completely useless.

**Comment by leahcimto** [comment]
Resolved. Projects and actions tab can not be deleted as they are standard github features.

**Comment by CodeGuy92** [comment]
Actually, they can be disabled. In the same place where you disable issues, you can find the option to disable projects. Check my website repo to see

Also, you can delete the actions tab by going to the actions tab in the repo settings and clicking the disabpe button.

This issue was not solved.

**Comment by leahcimto** [comment]
Done
